<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => "The Dandy Chair",
                'price' => 250,
                'image' => "https://www.ikea.com/us/en/images/products/stefan-chair-brown-black__0727320_pe735593_s5.jpg?f=xl",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],
            [
                'name' => "Minimal wooden vase",
                'price' => 150,
                'image' => "https://images.unsplash.com/photo-1582131503261-fca1d1c0589f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Accessories',
            ],
            [
                'name' => "The Silky Vase",
                'price' => 125,
                'image' => "https://silkyfactory.com/wp-content/uploads/2021/10/vaas5.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Homeware',
            ],
            [
                'name' => "Modern Lamp",
                'price' => 195,
                'image' => "https://images.unsplash.com/photo-1540932239986-30128078f3c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],
            [
                'name' => "Vintage Sofa",
                'price' => 195,
                'image' => "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "KOko Vase Set",
                'price' => 155,
                'image' => "https://m.media-amazon.com/images/I/61JxVujQN3L._AC_UF894,1000_QL80_.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Home',
            ],
            [
                'name' => "Rustic Farmhouse Chair",
                'price' => 125,
                'image' => "https://images.unsplash.com/photo-1581539250439-c96689b516dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],

            [
                'name' => "Elegant Sofa",
                'price' => 500,
                'image' => "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Elegant Chair",
                'price' => 175,
                'image' => "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],
            [
                'name' => "White",
                'price' => 700,
                'image' => "https://plus.unsplash.com/premium_photo-1683141389818-77fd3485334b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1538&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Vintage Sofa",
                'price' => 195,
                'image' => "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Bmw Vase Set",
                'price' => 155,
                'image' => "https://m.media-amazon.com/images/I/61JxVujQN3L._AC_UF894,1000_QL80_.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Accessories',
            ],


            [
                'name' => "Elegant Accent Chair",
                'price' => 135,
                'image' => "https://images.unsplash.com/photo-1589584649628-b597067e07a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],
            [
                'name' => "Vw Vase Set",
                'price' => 155,
                'image' => "https://m.media-amazon.com/images/I/61JxVujQN3L._AC_UF894,1000_QL80_.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Homeware',
            ],
            [
                'name' => "Modern2",
                'price' => 155,
                'image' => "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],

            [
                'name' => "Supra Vase Set",
                'price' => 155,
                'image' => "https://m.media-amazon.com/images/I/61JxVujQN3L._AC_UF894,1000_QL80_.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Homeware',
            ],
            [
                'name' => "Rustic Farmhouse Chair",
                'price' => 125,
                'image' => "https://images.unsplash.com/photo-1581539250439-c96689b516dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],
            [
                'name' => "Honda Vase Set",
                'price' => 155,
                'image' => "https://m.media-amazon.com/images/I/61JxVujQN3L._AC_UF894,1000_QL80_.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Accessories',
            ],
            [
                'name' => "Elegant Accent Chair",
                'price' => 135,
                'image' => "https://images.unsplash.com/photo-1589584649628-b597067e07a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],
            [
                'name' => "Reno Vase Set",
                'price' => 155,
                'image' => "https://m.media-amazon.com/images/I/61JxVujQN3L._AC_UF894,1000_QL80_.jpg",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Homeware',
            ],
            [
                'name' => "Elegant Chair",
                'price' => 175,
                'image' => "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=765&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Furniture',
            ],
            [
                'name' => "Modern Lamp",
                'price' => 195,
                'image' => "https://images.unsplash.com/photo-1540932239986-30128078f3c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],

            [
                'name' => "Vintage Lamp",
                'price' => 200,
                'image' => "https://images.unsplash.com/photo-1567459045800-4d77c81fc3f5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],
            [
                'name' => "Elegant Sofa",
                'price' => 500,
                'image' => "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Vintage Sofa",
                'price' => 195,
                'image' => "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Sofa",
                'price' => 195,
                'image' => "https://images.unsplash.com/photo-1540574163026-643ea20ade25?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',


            ],
            [
                'name' => "White",
                'price' => 700,
                'image' => "https://plus.unsplash.com/premium_photo-1683141389818-77fd3485334b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1538&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Modern Gray",
                'price' => 900,
                'image' => "https://images.unsplash.com/photo-1634497885778-152eb6fd543d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Sofas',
            ],
            [
                'name' => "Metallic",
                'price' => 100,
                'image' => "https://images.unsplash.com/photo-1542728928-1413d1894ed1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],
            [
                'name' => "Modern2",
                'price' => 155,
                'image' => "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=735&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],
            [
                'name' => "Modern Lamp",
                'price' => 250,
                'image' => "https://images.unsplash.com/photo-1636368208791-17b81ed832d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=729&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Light fittings',
            ],
            [
                'name' => "Vase",
                'price' => 50,
                'image' => "https://plus.unsplash.com/premium_photo-1681382743881-6afac0a7a556?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=880&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Accessories',
            ],
            [
                'name' => "Minimal wooden vase",
                'price' => 150,
                'image' => "https://images.unsplash.com/photo-1582131503261-fca1d1c0589f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Accessories',
            ],
            [
                'name' => "Minimalist",
                'price' => 250,
                'image' => "https://plus.unsplash.com/premium_photo-1676836059659-161e0d6ea49e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80",
                'description' => "NICE PRODUCT",
                'height' => '100cm',
                'width'=> '75cm',
                'depth'=> '45cm',
                'type' => 'Accessories',
            ],
        ]);
    }
}
